<a href="https://colab.research.google.com/github/gubei528/Hello-python/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
B = torch.tensor((1,2,3),dtype = torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [5]:
Y  = B.pow(2).sum()
Y.backward()
B.grad

tensor([2., 4., 6.])

In [9]:
c = torch.Tensor(2,3)
c

tensor([[1.4281e+12, 3.0681e-41, 3.7835e-44],
        [0.0000e+00,        nan, 6.4460e-44]])

In [7]:
## 创建一个与B维度相同的全1张量
D = torch.ones_like(B)
D

tensor([1., 1., 1.])

torch.**_like() # 系列函数生成与指定张量维度相同的张量
1.   torch.ones_like() 生成全1张量
2.   torch.zeros_like() 生成全0张量
3.   torch.rand_like()  生成随机张量
4.   torch.eye(3)    生成3 x 3的单位向量






In [10]:
torch.zeros_like(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.rand_like(c)

tensor([[0.6545, 0.5184, 0.2010],
        [0.8323, 0.5884, 0.0642]])

针对创建好的张量，使用c.new_**()系列函数创建出新的张量


*   c.new_full((3,3),fill_value = *)  填充*的*3 x 3*的张量
*   c.new_zeros((3,3))   3x3 的全0张量
*   c.new_empty((3,3))   3x3 的空张量
*   c.new_ones((3,3))   3x3 全1张量





In [14]:
# 使用D.new_tensor()将列表转换成张量
e = [[1,2],[3,4]]  # list
e = c.new_tensor(e)
e.type

<function Tensor.type>

Tensor 和 numpy 数据转换
*  将numpy数组转换为torch张量，使用torch.as_tensor() 函数和torch.from_numpy()函
数
*  torch.numpy()函数转换为numpy数组
*  **注：numpy默认生成的数组为float64类型的**

In [15]:
import numpy as np


In [17]:
F = np.ones((3,3))
F_tensor = torch.as_tensor(F)
F_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
F_tensor2 = torch.from_numpy(F)
F_tensor2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

生成随机数之前可以使用torch.manual_seed()函数，指定生成随机数种子，保障生成的随机数是可重复出现的

In [20]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.tensor(1.0))  # mean 指定随机数的均值，std参数指定随机数的标准差
# 若两个参数只有一个数，那么只会生成一个随机数，有多值的话，则会生成多个随机数
A

tensor(-0.1115)

In [23]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0,std = torch.arange(1,10.0))
A 

tensor([-0.1115,  0.2407, -1.1089, -0.9617, -5.9846,  1.2556, -6.8065, -6.0404,
         2.9151])

In [26]:
torch.rand(3,10)

tensor([[0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274, 0.3821, 0.6605, 0.8536,
         0.5932],
        [0.6367, 0.9826, 0.2745, 0.6584, 0.2775, 0.8573, 0.8993, 0.0390, 0.9268,
         0.7388],
        [0.7179, 0.7058, 0.9156, 0.4340, 0.0772, 0.3565, 0.1479, 0.5331, 0.4066,
         0.2318]])

In [27]:
torch.manual_seed(123)
b = torch.rand(3,10)
b

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
         0.7264],
        [0.3153, 0.6871, 0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274, 0.3821,
         0.6605],
        [0.8536, 0.5932, 0.6367, 0.9826, 0.2745, 0.6584, 0.2775, 0.8573, 0.8993,
         0.0390]])

In [28]:
torch.randn(3,3) # 生成服从标准正态分布的随机数张量

tensor([[-1.4168,  0.8429, -0.6307],
        [ 1.2340,  0.3127,  0.6972],
        [-0.9950, -1.1476, -0.9178]])

In [29]:
torch.randperm(10)  # 可将0-n（左闭右开）之间的整数进行随机排序后输出

tensor([3, 0, 8, 5, 7, 4, 1, 2, 6, 9])

In [30]:
## torch.arange()生成张量
torch.arange(start = 0,end = 10,step = 2)

tensor([0, 2, 4, 6, 8])

In [31]:
# 在范围内生成固定数量的等间隔的张量
torch.linspace(start = 1,end = 10,steps = 5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [32]:
# s生成以对数为间隔的张量
torch.logspace(start = 1,end = 10,steps = 5)

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])

In [33]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
# tensor.reshape()设置张量的形状和大小
a = torch.arange(12.0).reshape(3,4)
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
b = torch.reshape(input = a,shape = (2,-1))

In [45]:
 # 将张量a的形状设置为张量b相同的大小
B = torch.arange(10.0,19.0).reshape(3,3)
a.resize_as_(B)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [48]:
# 使用.expand()方法对张量的维度进行扩展
# A.expand_as() 张量A根据张量C的形状大小进行扩展
A = torch.arange(3)
b = A.expand(3,-1)

In [52]:
A

tensor([0, 1, 2])

In [49]:
b

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [51]:
c = torch.arange(6).reshape(2,3)
b = A.expand_as(c)
b

tensor([[0, 1, 2],
        [0, 1, 2]])

In [54]:
# 使用张量的.repeat()方法，将整个张根据指定的形状进行重复填充，得到新的张量
D = b.repeat(1,2,2)
D

tensor([[[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]]])